import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/navbar'


/**navbar is above the main which theoredically contains everything. This ensures it is always on top...
      PLANNING:
      Hamburger menu to keep the menu small on mobile
      put logo on there
      keep it slim
      button to scroll back to top
      */
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Navbar title="faq">

      </Navbar>

      <main className={styles.main}>




      </main>


      <script>
        
      </script>
    </>
  )
}
