import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/navbar'
import Reviews from '../components/reviews'
import ImageSlideShow from "../components/imgSlideShow"
import BeforeAfter from "../components/beforeAfter"
import PlaceholderImg from "../public/ImgSldShow1.png"
import Link from 'next/link'
import GenericTitle from '@/components/GenericTitle'
import Article from '@/components/Article'

/**
      PLANNING:
      Hamburger menu to keep the menu small on mobile
      put logo on there
      keep it slim
      button to scroll back to top
      */
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Martham Construction</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Navbar title="home" />

      <main className={styles.main}>

        <ImageSlideShow />
        <title className={styles.title}>Martham Construction: Qualité, Fiabilité; Notre Spécialitée.</title>

        <Article 
        containerStyle={{flexDirection:"row-reverse"}} 
        image={PlaceholderImg} 
        title={"Notre Histoire"} 
        body={"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui,quia illum quam minima dolorum illo ad consequuntur earum inventore ratione,iste minus rerum, ex vero molestiae corporis atque sapiente voluptatem?Lorem ipsum dolor sit amet consectetur adipisicing elit.quia illum quam minima dolorum illo ad consequuntur earum inventore ratione, (+- 50 mots)"}
        link={"https://www.youtube.com/watch?v=dQw4w9WgXcQ"}
        linkName={"Des Questions?"}
        />

        <Article 
        containerStyle={{alignSelf:"last baseline"}}
        image={PlaceholderImg}
        title={"Nos Services"}
        body={"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui,quia illum quam minima dolorum illo ad consequuntur earum inventore ratione,iste minus rerum, ex vero molestiae corporis atque sapiente voluptatem? (+- 30 mots)"}
        additionals={'<div style={{ height: "30px" }} /><li>Service 1</li><li>Service 2</li><li>Et plus encore!</li>'}
        link={"https://www.youtube.com/watch?v=dQw4w9WgXcQ"}
        linkName={"Découvrir tous nos services"}
        />

        <GenericTitle Title="Témoignages"/>

        <Reviews />

        <BeforeAfter />

        <GenericTitle Title="Des Questions?" Style={{marginBottom:"50px"}}/>

        <div className={styles.IndexFaqButtonTopLevel}>
          Pour plus de renseignements, référez vous à notre foire aux questions où les questions
          les plus courantes sont posées
          <div className={styles.IndexFaqButtonContainer} >
            <Link className={styles.IndexFaqButton} href="/faq">Foire Aux Questions</Link>
          </div>
        </div>


      </main>


      <script>

      </script>
    </>
  )
}
