import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/navbar'
import next, { NextApiResponse, NextApiRequest } from "next"
import getServices from '../lib/getServices'
import { debug } from "console"
const inter = Inter({ subsets: ['latin'] })
import PlaceholderImg from "../public/ImgSldShow1.png"

export async function getStaticProps() {
  const response = await getServices()
  const data = response.map( item => ({ id: item.Id.toString(), title: item.Title, image: item.ImageUrl, desc: item.Description, outside: item.Outside }))


  return {
    props: { data },
  }
}

interface Service {
  id: string;
  title: string;
  image: string;
  desc: string;
  outside: boolean;
  cleanName: string;
}

export default function Home({ data }: { data: Service[] }) {

  /*          Placeholder: les icones sont juste des references, style nest pas complet.
  Ici, on rapelle les gens daller voir nos devis gratuit avec un lien. Aussi on met une phrase catchy*/
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Navbar title="service">

      </Navbar>

      <main className={styles.main}>

        <div className={styles.servicesMainTitle}>Nos Services</div>
        <div className={styles.servicesMainTitleContainer}>
          <div className={styles.servicesMainTitleBody}>
            <div style={{ padding: "0px 10%", textAlign: "justify" }}>
              Chez Martham, la qualité est notre priorité numéro 1. Nous en faisont notre mission de vous offrir
              un service rapide, de qualité tout en conservant un prix avantageux.
              .
            </div>

            <a href='contact' className={`${styles.servicesTitleContactButton}`}> Recevez un devis gratuitement!</a>
          </div>


        </div>


        <div className={styles.servicesBodyTitle}>Extérieur</div>
        <div className={styles.servicesBodyTitleContainer}>
          <div className={styles.servicesBodyTitleBody}>

          Services professionnels pour extérieur:
            <div className={styles.servicesListContainer}>
              {data.map(item => (
                (item.outside) &&
                <a href={"services/" + item.title} key={item.id} className={styles.servicesList}>
                  {item.title}
                </a>

              ))}
            </div>
            <a href='contact' className={`${styles.servicesBodyButton}`} style={{marginBottom:"-50px"}}>Voir nos realisations pour les travaux extérieurs</a>
          </div>
          <Image src={PlaceholderImg} alt="/" width={640} height={426} className={styles.servicesImage} />

        </div>


        <div className={styles.servicesBodyTitle}>Intérieur</div>
        <div className={styles.servicesBodyTitleContainer}>
          <div className={styles.servicesBodyTitleBody}>

          Services professionnels pour intérieur:
            <div className={styles.servicesListContainer}>
              {data.map(item => (
                (!item.outside) &&
                <a href={"services/" + item.title} key={item.id} className={styles.servicesList}>
                  {item.title}
                </a>

              ))}
            </div>
            <a href='contact' className={`${styles.servicesBodyButton}`} style={{marginBottom:"-50px"}}>Voir nos realisations pour les travaux intérieurs</a>
          </div>
          <Image src={PlaceholderImg} alt="/" width={640} height={426} className={styles.servicesImage} />

        </div>

      </main>


      <script>

      </script>
    </>
  )

}


/* This uses a database to place stuff, kinda usefull so ill put it here
{data.map(item => (
          <div key={item.id} className={styles.servicesCard}>
            <div className={styles.servicesTitle}>
              {item.title}
              <div className={styles.servicesBody}>
                {item.desc}
              </div>
            </div>
            <div className={styles.servicesThumbnail}>
              <Image src={item.image} alt="/" width={640} height={426} className={styles.servicesImage} />
            </div>
          </div>
        ))}
*/
