import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from './navbar'
import next, { NextApiResponse, NextApiRequest } from "next"
import getServices from '../lib/getServices'
import { debug } from "console"
const inter = Inter({ subsets: ['latin'] })
import PlaceholderImg from "../public/ImgSldShow1.png"

export async function getServerSideProps() {
  const response = await getServices()
  const data = response.map(item => ({ id: item.Id.toString(), title: item.Title, image: item.ImageUrl, desc: item.Description }))

  console.log(console.log(data.map(item => item.title)))
  return {
    props: { data },
  }
}

interface Service {
  id: string;
  title: string;
  image: string;
  desc: string;
}

export default function Home({ data }: { data: Service[] }) {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Navbar title="service">

      </Navbar>

      <main className={styles.main}>

        <div className={styles.servicesMainTitle}>Nos Services</div>
        <div style={{ color: "black" }} className={styles.servicesMainTitleBody}>
          Placeholder: les icones sont juste des references, style nest pas complet.Ici, on rapelle les gens d'aller voir nos devis gratuit avec un lien. Aussi on met une phrase catchy
          <br/><br/>
          Chez Martham, la qualité est notre priorité numéro 1. Nous en faisont notre mission de vous offrir 
          un service rapide, de qualité tout en conservant un prix avantageux. Nos employés ..
          .
        </div>

        {data.map(item => (
          <div key={item.id} className={styles.servicesCard}>
            <div className={styles.servicesTitle}>
              {item.title}
              <div className={styles.servicesBody}>
                {item.desc}
              </div>
            </div>
            <div className={styles.servicesThumbnail}>
              <Image src={item.image} alt="/" width={640} height={426} className={styles.servicesImage} />
            </div>
          </div>
        ))}


      </main>


      <script>

      </script>
    </>
  )

}



